### ISSUE TITLE
Question: Blockbench support?

### ISSUE THREAD

**Issue by Raft08** [Godlander/objmc#11]
Hello, i'm trying to add a models to my Custom Block but i want to resize the model first. I didn't test if it does work ingame.

But when i umport it i makes that: 

![image](https://user-images.githubusercontent.com/72615320/165783648-9767e91f-7f25-45ff-9ead-dc8d1184b67a.png)

So i just want to know if you make support for that in the future

PS: Idk realy what shaders ect.. , i'm just using a model that i downloaded on the web

Thanks, Raft

**Comment by Godlander** [comment]
model edits should be done on the obj model, not the objmc output.
