### ISSUE TITLE
Rotate model, questions

### ISSUE THREAD

**Issue by GeorgeMixas** [Godlander/objmc#12]
Hello, I have a few questions that I would like to ask, is it possible to rotate how the model appears when the player is in first/third person view instead of holding it like a normal item? 

Will the resourcepack generated by objmc work on future Minecraft versions and are there any plans at all to make this work with optifine/sodium?

Also, how would I go about making the model rotate when thrown on the ground similar to how vanilla items rotate?

and lastly a huge thank you for making this tool!!!, people have been waiting years to use obj files in minecraft.

**Comment by MrGazdag** [comment]
The objmc shaders are subject to breaking with every update, and it is not being made backwards compatible. objmc is supposed to support the latest version only, so there might be backwards-incompatible changes further down the line, thus you might have convert the models again for future updates.

objmc does not work in all cases with optifine/sodium, as objmc modifies block/entity shaders, these mods override some rendering processes.

You can try to make the the item rotate on the ground, by creating an alternate item which has a rotation animation on the model. You will have to change the item on the ground with commands/plugins though. This is not necessarily the best solution for this though, and you'll have to get the rotation speed right.

Changing the way the model renders in firstperson/thirdperson might be possible, using some transformation methods with the item models, though Godlander might know more about this.

I hope I answered some of your questions, and i agree with you: thank you Godlander for making this tool.
