### ISSUE TITLE
Non full blocks don't render models

### ISSUE THREAD

**Issue by tobyplowy** [Godlander/objmc#16]
Models don't render on non full blocks. For example I wanna add a model to my amethyst but can't as it doesn't render but if I put the same model on to cobblestone it works just fine. 

![image](https://user-images.githubusercontent.com/16853304/178093840-99d47b18-aa38-4cbd-8ba1-1ed4f3cfb8ed.png)

**Comment by Godlander** [comment]
thats because `rendertype_cutout` isnt in the list due to some weird edge issues

you can just duplicate `rendertype_translucent` and rename the copy to `rendertype_cutout`

**Comment by tobyplowy** [comment]
@Godlander Thanks for the reply :D
Sadly this doesn't seem to work for some reason?
 
 rendertype_cutout has the same content as rendertype_translucent.

**Comment by tobyplowy** [comment]
Also the issues really that bad? I'd like to make a real full project with this and use a decent amount of models. 
This project basically makes 80% of my minecraft model limitations go bye bye I can do incredible things with this XD

**Comment by Godlander** [comment]
well the issues that im having seem hardware specific, and i cant pinpoint what causes it.
if ur going to use objmc i suggest you set up something that allows u to mass regenerate the models.
while any version of the script/resourcepack/minecraft that works will probably remain to work, i cant guarantee anything for future versions of them, so if any change happen to the game or my code, you may have to either not upgrade or regenerate all models for new versions

**Comment by Godlander** [comment]
resolved on discord, turned out to be optifine mipmapping issue
