### ISSUE TITLE
Scale and Autorotate in UI dont work

### ISSUE THREAD

**Issue by Web7283** [Godlander/objmc#19]
i think that for some reason the program doesn't receive the arguments. I tried without the UI, no luck.

**Comment by Godlander** [comment]
are you sure you're replacing and reloading the output afterwards correctly?
all the data are encoded in the texture, so if you change scale/autorotate you will have to replace the texture in your resourcepack with the newly generated one.

**Comment by Web7283** [comment]
got it to work. offset doesn't though

**Comment by Godlander** [comment]
i found the problem, should be fixed

**Comment by Web7283** [comment]
thanks! 👍
