### ISSUE TITLE
[Bug] Generating the same model multiple times in a row keeps adding i*nfaces to the .json only when using objmc.exe

### ISSUE THREAD

**Issue by mattcarter11** [Godlander/objmc#20]
This bug is only present when using the _objmc.exe_. Basically, each time you generate the _.json_ in the same program instance, the file regenerates but it has ` i*nfaces` where i is the times you have generated the model in a row.

This is very bad because if you start tweaking the settings and generating the model multiple times you end up with big files and with
unecesar geometry.

In the following image is an example of generating the same model 4 times in a row, with the model only having 42 faces, but each time we get `i*42` faces.

![image](https://user-images.githubusercontent.com/38189440/201762861-c4cdedd6-0195-4fe0-b63b-42ac14540f9b.png)

**Comment by Godlander** [comment]
oops i forgot to delete the exe, its outdated anyway. dont use it
