### ISSUE TITLE
No module named "PIL"

### ISSUE THREAD

**Issue by thesun101lolhaha** [Godlander/objmc#21]
There's an error in line 9 of your code, it does not allow the program to work.

"line 9, in <module>
      from PIL import Image, ImageOps
ModuleNotFoundError: No module named 'PIL'"

I use Anaconda, and it says that it already has the Pillow thing. What is happening?

**Comment by Godlander** [comment]
idk much about anaconda
but i think you probably dont have pillow, or dont have it in the right place that the script can find.

**Comment by adrienduvalet** [comment]
thesun101lolhaha I advice you to use PyCharm instead of Anaconda.
