### ISSUE TITLE
Mutliple textures support?

### ISSUE THREAD

**Issue by tjwhang** [Godlander/objmc#26]
Does objmc supports multiple textures with different sizes?
I tried it but it crashed so maybe I was doing it in the wrong way?
I also tried including only one texture from them, and it won't work either. The data pixel does not appear.

**Comment by tjwhang** [comment]
OK never mind.. I should have read the README carefully... 
but I really would like it if objmc supports multi textures..

**Comment by Godlander** [comment]
for now you will need to stitch or bake the textures together with some other program
i dont think i can make a texture stitcher better than those other programs so i dont feel too inclined to do it
