### ISSUE TITLE
Models are invisible

### ISSUE THREAD

**Issue by Zytatus** [Godlander/objmc#32]
Hello! I have tried obj-mc and made a model and it was invisible. I put in the resourcepack from the folder in obj-mc and the shuba was also invisible. I have my graphics settings on "Faboulus!" and this is my command: /summon minecraft:armor_stand ~ ~ ~ {ShowArms:1b,ArmorItems:[{},{},{},{id:"minecraft:potion",Count:1b,tag:{CustomModelData:1,CustomPotionColor:0}}],ArmorDropChances:[0f,0f,0f,0f]}  but there was no shuba. Any ideas?

**Comment by Godlander** [comment]
if the default models are invisible then most likely it means you arn't playing the right version of the game

make sure you are in vanilla 1.19.4+
