### ISSUE TITLE
Scaling not working

### ISSUE THREAD

**Issue by HC-Emro** [Godlander/objmc#35]
The scaling option is just not working, my models are either too big or too small, and when I enter a value for the scale, it doesn't change the size at all.

**Comment by HC-Emro** [comment]
I also modified the obj model on blockbench and blender being careful to export it correctly but when I convert it to json there is still the old model. How is that even possible?

**Comment by Godlander** [comment]
if its a gui model in 1.20 then it is a known issue and ill fix in future

if its an in world model, try rescaling the model in blender or another modeling software. 1 unit in blender should be 1 block ingame. in blockbench 16 units is 1 block ingame

**Comment by HC-Emro** [comment]
1.19.4, I already did it, on blender and blockbench. I scaled the model 10x but it's still have the same size as the first model. I can't understand how it's possible.

**Comment by Godlander** [comment]
it sounds like you didnt update the actual resourcepack

re export with objmc and replace the texture and model again in the resourcepack
