### ISSUE TITLE
Weird Rotations

### ISSUE THREAD

**Issue by AntiWither** [Godlander/objmc#36]
I have been using objmc for a while testing this out but every time it ends up with things like this

![2023-06-24_18 11 00](https://github.com/Godlander/objmc/assets/131559798/84d43fe9-8a58-4a4f-90f9-25c122a7266b)

I'm not sure why this happened as the 3d model itself wasn't rotated at all

**Comment by AntiWither** [comment]
also the animation on this model doesn't work

**Comment by Godlander** [comment]
if you're using potion item, it is likely due to colorbehavior being set to rotations, and the potion having a color thats not zero
