### ISSUE TITLE
PLEASSEEEEE add a option for backface culling

### ISSUE THREAD

**Issue by hgamingyt** [Godlander/objmc#38]
pleassseeeee

**Comment by Godlander** [comment]
this is impossible due to how objmc is implemented, and due to how minecraft models work in general

**Comment by hgamingyt** [comment]
ok

**Comment by Godlander** [comment]
you will have to handle culling yourself either by loading/unloading pieces of a large model, or use 16^3 chunks of block models so that minecraft default subchunk frustum culling automatically does it
