### ISSUE TITLE
sodium shader support mod

### ISSUE THREAD

**Issue by tankorange** [Godlander/objmc#39]
So there's a mod for sodium that can fix vanilla shaders but it uses a slightly different code for the shader itself so I was just wondering if there's a way for you to make a version that uses that changed code for people who use sodium(let me know if this is the the wrong place to ask this! I'm kinda new to GitHub.)

**Comment by Godlander** [comment]
what is the difference? would help if you provide something specific

if something can be added to allow sodium compat and doesn't break anything for vanilla then i will consider it

**Comment by tankorange** [comment]
from what ive read about its vanilla like but with changed names for in/out/uniform values. im not a programmer and i dont understand that stuff but i did find a link to sodiums values i think https://github.com/CaffeineMC/sodium-fabric/tree/1.20/dev/src/main/resources/assets/sodium/shaders/blocks. let me know if this is more specific

**Comment by Godlander** [comment]
those are internal shaders for sodium, and are not modifiable and not planned to be modifiable with resourcepacks

**Comment by tankorange** [comment]
Ok thanks for letting me know. its a bummer that vanilla shaders get broken by sodium and optifine.

**Comment by Godlander** [comment]
hm, sodium devs said they do not support this.

i'll talk to DartCat25 and see if this is possible

**Comment by Godlander** [comment]
closing, see https://github.com/Godlander/objmc/issues/47
