### ISSUE TITLE
Error when putting files in obj-mc

### ISSUE THREAD

**Issue by Zytatus** [Godlander/objmc#41]
![image](https://github.com/Godlander/objmc/assets/132785727/f57596ad-a068-4479-ac95-42f6249f9467)
Have this problem when I put any file in obj-mc
These are my settings:
![image](https://github.com/Godlander/objmc/assets/132785727/bc012248-ecaa-4bdc-90ee-7378196904c7)

**Comment by Zytatus** [comment]
Had to open it directly or as admin or with sudo. Some of these should do the trick ^^

**Comment by Godlander** [comment]
ah yea that tends to happen when you're trying to write into ur system's user folder
