### ISSUE TITLE
Objmc says "permission denied" when I tried to start the program (not opening it)

### ISSUE THREAD

**Issue by AhmadTheProYT** [Godlander/objmc#44]

**Comment by Godlander** [comment]
try running it with admin perms, or move it out of system drive user folder

**Comment by AhmadTheProYT** [comment]
still doesnt generate anything. I moved it out of the system folder to my external drive, but i cant figure out how to run it with admin perms tho, theres no option to do that when i right click it

**Comment by Godlander** [comment]
sounds like you arn't the administrator user on your machine, i can't help with that sorry.

**Comment by AhmadTheProYT** [comment]
I solved it, i downloaded python from the microsoft store and thats why it doesnt have admin perms. REMEMBER TO DOWNLOAD PYTHON ONLY FROM THE SITE OR IT WILL NOT WORK

**Comment by m-i-n-i-q-q** [comment]
> I solved it, i downloaded python from the microsoft store and thats why it doesnt have admin perms. REMEMBER TO DOWNLOAD PYTHON ONLY FROM THE SITE OR IT WILL NOT WORK

I tried exactly as you said,BUT IT STILL DOESN'T WORK.
