### ISSUE TITLE
How can I get a model on a block, not an item?

### ISSUE THREAD

**Issue by super-15** [Godlander/objmc#45]
Whenever I put the JSON file into the blocks folder in the texture pack and name it as a block, the model shows when I hold the block, put it in an item frame, etc. but when I place the block down it just shows the regular model and texture

**Comment by Felix14-v2** [comment]
Well, you cant, this is a technical limitation. Iirc, it is possible to make it work with glass blocks, but I think that current implementation is still better.

**Comment by Godlander** [comment]
sounds like you're using modded game or something

it should just work
