### ISSUE TITLE
Objmc is not working with custom model data

### ISSUE THREAD

**Issue by AhmadTheProYT** [Godlander/objmc#48]

**Comment by Godlander** [comment]
cannot reproduce, likely user error.
can you provide details of how it is "not working" and what exactly you did step by step

**Comment by AhmadTheProYT** [comment]
Alright so :
- I got the model and it's textures
- imported it into objmc (it's worth mentioning the model does work when it's in a regular resource pack)
- renamed it to what I wanted it's name to be (since custom models can be named different things)
- and then put it in the files after it generates the model and textures
- does not even render ingame

**Comment by Godlander** [comment]
the objmc output json models and textures behave just like any other vanilla model, and can be used as an override for custommodeldata. as long as the model points to the texture correctly, it should show.
