### ISSUE TITLE
Cannot convert .obj file.

### ISSUE THREAD

**Issue by Web7283** [Godlander/objmc#5]
The script just won't work and I'm not sure why. I ran in in command prompt and got this error message _line 65, in <listcomp>
    d["positions"].append([float(i) for i in line.strip().split(" ")[1:]])
ValueError: could not convert string to float: ''_

**Comment by Godlander** [comment]
ah, remove all double spaces and trailing spaces from the obj file.
i gotta change the script to use regex instead of hard match sometime

**Comment by Web7283** [comment]
Thx, it works!

**Comment by Godlander** [comment]
fixd, now script can handle any amount of spaces
