### ISSUE TITLE
Long models and shaders 

### ISSUE THREAD

**Issue by Zytatus** [Godlander/objmc#50]
Hi there! I tried importing an animation with 940 frames and when I started minecraft, the textures of my whole world where corrupted and I had to restart mc and put out the texturepack. Is there any way to fix that? Also, do you know wich part in a optifine/sodium shader collides with obj-mc so the models wont load when active? Thanks ^^

**Comment by Godlander** [comment]
sounds like a vram issue to me, try to make your resulting texture as square as possible and use less frames, let interpolation do the work.

every part. just dont use mods.
