### ISSUE TITLE
Playing animations backwards

### ISSUE THREAD

**Issue by Zytatus** [Godlander/objmc#51]
Hi is it possible to play animations backwards? I've tried to rename the objs so ...20 is ...1 and ...19 is ...2 and so on so the animation gets played backwards, but it didn't work and I don't know why? Is there a way to fix that? Thanks :)

**Comment by Godlander** [comment]
if you encode the models in reverse order the animation should look backwards when played forwards
that should work, so u mightv done something wrong in the process
