### ISSUE TITLE
Why is my car looks weird ?

### ISSUE THREAD

**Issue by HC-Emro** [Godlander/objmc#54]
Here is the screen and the obj zip (I changed the .jpg to .png before rendering).
![2023-12-22_07 28 41](https://github.com/Godlander/objmc/assets/56135028/40ac3317-ad23-4ebf-b765-ab60bab0e87c)
[uploads_files_1017599_Jeep_Renegade_2016_obj (2).zip](https://github.com/Godlander/objmc/files/13749020/uploads_files_1017599_Jeep_Renegade_2016_obj.2.zip)
The link of the model : https://www.cgtrader.com/free-3d-models/car/suv/jeep-renegade-a-5-doors-compact-suv-from-2016

**Comment by HC-Emro** [comment]
https://www.cgtrader.com/items/3132934/download-page
Same for this car, this time it has his own .png texture so Idk why it doesn't work.
![2023-12-22_07 41 26](https://github.com/Godlander/objmc/assets/56135028/b8a7a195-41bc-49e8-b97b-55e15ce8495d)

**Comment by Godlander** [comment]
try triangulating the model first
