### ISSUE TITLE
r1w21

### ISSUE THREAD

**Issue by dan22315** [Godlander/objmc#60]
[81-725.zip](https://github.com/Godlander/objmc/files/14549991/81-725.zip)
**Description**
what is the bug?

**Reproduction**
steps to reproduce
(e.g. how the model was produced, conversion settings, resourcepack setup, etc)

**Screenshots**
attach screenshots or videos of the problem

**Environment:**
- Operating System
- Game Version (only vanilla will be supported)
- GPU / CPU
(F3 menu contains important information)

**Additional context**

**Comment by Godlander** [comment]
uh, there seems to be no report. try writing something about what you're reporting
