### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by Theblackdragon5** [Godlander/objmc#62]
**Description**
The Start Button is not working on Mac

**Reproduction**
I selected a Obj file to convert, but it shows an error

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "/Users/minecraft/Documents/objmc/objmc.py", line 700, in start
>     objmc(objs, texs, output, scale, offset, duration, easing, interpolation, colorbehavior, autorotate, autoplay, flipuv, noshadow, nopow)
>   File "/Users/minecraft/Documents/objmc/objmc.py", line 320, in objmc
>     tex = Image.open(texs[0])
>           ^^^^^^^^^^^^^^^^^^^
>   File "/Users/minecraft/objmc/lib/python3.11/site-packages/PIL/Image.py", line 3277, in open
>     fp = builtins.open(filename, "rb")
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> IsADirectoryError: [Errno 21] Is a directory: '/Users/minecraft/Documents/objmc'

**Environment:**
macOS High Sierra v. 10.13.6
- Game Version: 1.20.4
- GPU / CPU: 2,8 GHz Quad-Core Intel Xeon

**Comment by Godlander** [comment]
looks like you selected a folder instead of a file

**Comment by Theblackdragon5** [comment]
> looks like you selected a folder instead of a file

But I did select an obj

**Comment by Theblackdragon5** [comment]
> looks like you selected a folder instead of a file

![Uploading objmc.jpeg…]()

**Comment by Theblackdragon5** [comment]
> looks like you selected a folder instead of a file

![objmc](https://github.com/Godlander/objmc/assets/130586375/6f6b1430-86d0-4455-9fd7-7ec0513cea26)

**Comment by Godlander** [comment]
you have not selected a texture

**Comment by Theblackdragon5** [comment]
> you have not selected a texture

Do I have to pick one? What if I don’t have a texture?

**Comment by vadim-soude** [comment]
There is no default texture that the script can use, so yes, you have to provide a texture for the model
