### ISSUE TITLE
When i try to load resource pack

### ISSUE THREAD

**Issue by Adawasda** [Godlander/objmc#68]
**Description**

When I load a resource pack with core shaders, it doesn't load.

**Reproduction**
steps to reproduce
 used the resource pack that was in the project, when I use Optifine everything works, but when I use fabric 1.20.1 (without mods) and vanilla 1.20.1 it stops working, giving this error: java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
>> 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
>> 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
>> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
>> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
>> 	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
>> 	at net.minecraft.client.main.Main.main(Main.java:250) ~[Fabric%201.20.1.jar:?]
>> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
>> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
>> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
>> Caused by: java.lang.RuntimeException: could not reload shaders
>> 	at net.minecraft.class_757.method_34538(class_757.java:567) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_757$1.method_45777(class_757.java:441) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_757$1.method_18788(class_757.java:418) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
>> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
>> 	... 12 more
>> Caused by: net.minecraft.class_2973: Invalid shaders/core/particle.json: Couldn't compile vertex program (vanilla, particle) : ERROR: 0:23: 'fog_distance' : no matching overloaded function found 
>> ERROR: 0:23: '' : compilation terminated 
>> ERROR: 2 compilation errors.  No code generated.
>> 	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_5944.<init>(class_5944.java:203) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_757.method_34538(class_757.java:505) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_757$1.method_45777(class_757.java:441) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_757$1.method_18788(class_757.java:418) ~[client-intermediary.jar:?]
>> 	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
>> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
>> 	... 12 more
>> Caused by: java.io.IOException: Couldn't compile vertex program (vanilla, particle) : ERROR: 0:23: 'fog_distance' : no matching overloaded function found 
>> ERROR: 0:23: '' : compilation terminate

**Screenshots**
attach screenshots or videos of the problem

**Environment:**
- Windows 11
- Vanilla 1.20.1
- GPU / CPU
(F3 menu contains important information)

**Comment by Adawasda** [comment]
won't work*. When i use optifine, it works. But when i load it with vanilla minecraft it didnt work

**Comment by Godlander** [comment]
objmc is made for vanilla latest release. for previous versions you can try going back to a previous commit, but i cant provide support
