### ISSUE TITLE
Experience orb color

### ISSUE THREAD

**Issue by JustJabka** [Godlander/objmc#70]
**Description**
Using the shader from the OBJ MC resourcepack, the color of the experience orb becomes dark.

**Screenshots**
![image](https://github.com/Godlander/objmc/assets/117545035/ba4d36c1-2510-4661-8528-9273fa031510)

**Environment:**
- Windows 10
- 24w19b
- i3-1115G4 / intagrated GPU

**Comment by Godlander** [comment]
fixed by https://github.com/Godlander/objmc/commit/940ed38dd0ca87739aa7fadd7ff5924aaf4227de
