### ISSUE TITLE
Item Textures are black

### ISSUE THREAD

**Issue by maksblack12** [Godlander/objmc#71]
**Desciption**
using the shader almost all the item textures become black

**Screenshots**
![2024-05-17_14 27 29](https://github.com/Godlander/objmc/assets/109464984/5a94f5cb-1d64-4712-a95f-9a72a693dee3)

**Environment**
- windows
- 1.20.6

**Comment by Godlander** [comment]
i believe this may be duplicate of #59 
the issue seems very inconsistent and i cannot pinpoint what causes it

**Comment by Godlander** [comment]
fixed by https://github.com/Godlander/objmc/commit/940ed38dd0ca87739aa7fadd7ff5924aaf4227de
