### ISSUE TITLE
ZIP resources not working

### ISSUE THREAD

**Issue by belnek** [Godlander/objmc#74]
**Description**
OBJMC Resourcepack not working in a ZIP archive. Minecraft doesn't see it.

**Environment:**
- Operating System: Win 7
- Game Version: 1.20.4

**Comment by vadim-soude** [comment]
Are you sure that the zip you have don't have a folder before the resource pack itself ? 

And on another note, the current version of Objmc is compatible with minecraft version after 1.20.4.

**Comment by belnek** [comment]
Yes, I archived everything correctly, according to the rules. As for the version, I downloaded an old version of the script that supports 1.20.4. Everything works well in the unzipped form.

**Comment by vadim-soude** [comment]
Could you provide the log of your client when you try to load the rp ?

**Comment by belnek** [comment]
Link on RP, if need: [click](https://www.dropbox.com/scl/fi/8doq2bvkx3sltl0djt28r/objmc.zip?rlkey=j2rji2zerpjg3uskhvpbp8754&st=5ay86eqy&dl=0)

**Comment by belnek** [comment]
The problem turned out to be in the backup file with the extension _.jso_. 
It is very strange that it worked in folder mode, without an archive, 
I thought that minecraft ignores files without .json in models. 

Anyway, this is a problem of my inattention, thanks for the help.
