### ISSUE TITLE
does not work in 1.20.1

### ISSUE THREAD

**Issue by okil6** [Godlander/objmc#75]
**it says failed to load in 1.20.1 pls help or send an other version**
what is the bug?

**Reproduction**
steps to reproduce
(e.g. how the model was produced, conversion settings, resourcepack setup, etc)

**Screenshots**
attach screenshots or videos of the problem

**Environment:**
- Operating System
- Game Version (only vanilla will be supported)
- GPU / CPU
(F3 menu contains important information)

**Additional context**

**Comment by Godlander** [comment]
you can download a previous version from github commit history
