### ISSUE TITLE
transparency issues with models

### ISSUE THREAD

**Issue by tankorange** [Godlander/objmc#76]
**Description**
transparent textures seem to be a little bit buggy

**Reproduction**
steps to reproduce
have a semi transparent texture in front of another texture

**Screenshots**
![2024-06-23_05 00 30](https://github.com/Godlander/objmc/assets/108636609/4897c5dc-0274-4fd4-ad09-8e8f82aad841)
![2024-06-23_05 02 20](https://github.com/Godlander/objmc/assets/108636609/d172e2e8-022f-4728-b0d2-c1d9d19f1f82)

**Environment:**
- windows 10
- 1.20.6
- core i5 10400f1660 super
(F3 menu contains important information)

**Comment by Godlander** [comment]
this is an issue with minecraft rendering, not something that can be fixed with shaders

**Comment by Felix14-v2** [comment]
You can try Fabulous graphics to fix that, but I think it will break more than fix.
