### ISSUE TITLE
Model invisible ingame

### ISSUE THREAD

**Issue by Zytatus** [Godlander/objmc#77]
**Description**
I tried to import a model in MC via objmc (I did multiple by now), but it was a .gltf model so I imported it in blender and exported it as obj -> model is invisible in MC. I imported the obj from blender in BB and exported it again as a obj. Yesterday this method (Idk why) made the model show up in game. Today this way of doing it doesnt work anymore and I don't even know why it worked in the first place. 

![image](https://github.com/Godlander/objmc/assets/132785727/99ae5e4e-1c22-44b3-9ab7-28ca3a79e532)
![image](https://github.com/Godlander/objmc/assets/132785727/dd3c1e69-fa81-43b0-b5b3-3a42f444171e)
![image](https://github.com/Godlander/objmc/assets/132785727/2e8bf830-36b6-478d-b462-337aa076809c)
![image](https://github.com/Godlander/objmc/assets/132785727/4e3beeeb-d10e-43d4-8783-7e8d418ed0d9)
In 3D viewer it clearly shows it.
![image](https://github.com/Godlander/objmc/assets/132785727/c3673190-b8bd-4b5a-85c8-df47043bd54b)

**Environment:**
- Win11
- 1.20.1
- Rx6700xt / Ryzen 5 5600x

**Comment by Zytatus** [comment]
![image](https://github.com/Godlander/objmc/assets/132785727/f268cb58-4035-48a8-9bd6-eb51aa95c568)

**Comment by Godlander** [comment]
check game log, nothing here suggests its a bug with objmc itself

**Comment by Zytatus** [comment]
There is nothing in the log about the model (police_car) or the texture

**Comment by Zytatus** [comment]
The texture was mirrored
![gltf_embedded_0](https://github.com/Godlander/objmc/assets/132785727/36344bf6-99a0-44b6-8076-729da55aad4c)
and since the other 3/4 of the texture where just transparent it of course didn't load anything, I just realised as I looked at the UV

**Comment by Zytatus** [comment]
Such a stupid mistake like wtf
