### ISSUE TITLE
The "optifine compat" shader failed to load

### ISSUE THREAD

**Issue by Daminator4113** [Godlander/objmc#8]
Here's the error I have in the consol : 

`Caused by: java.lang.RuntimeException: could not reload shaders`
`	at epe.b(GameRenderer.java:706)`
`	at epe.a(GameRenderer.java:410)`
`	at afl.a(SourceFile:15)`
`	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)`
`	... 121 more`
`Caused by: yk: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (objmc_optifine, render/block) : 0(46) : error C1503: undefined variable "fog_distance"`
`	at yk.a(SourceFile:48)`
`	at epw.<init>(ShaderInstance.java:225)`
`	at epw.<init>(ShaderInstance.java:103)`
`	at epe.b(GameRenderer.java:528)`
`	... 124 more`
`Caused by: java.io.IOException: Couldn't compile vertex program (objmc_optifine, render/block) : 0(46) : error C1503: undefined variable "fog_distance"`
`	at dry.b(Program.java:94)`
`	at dry.a(Program.java:55)`
`	at epw.a(ShaderInstance.java:269)`
`	at epw.<init>(ShaderInstance.java:198)`
`	... 126 more`

**Comment by Godlander** [comment]
it seems you're running on 1.18.1, not the latest version.
you should be able to fix this by adding the `fog.glsl` from the main branch, located at `assets/minecraft/shaders/include/fog.glsl`

**Comment by Daminator4113** [comment]
Thank's, it works with the fog.glsl file of the main branch, the file is missing in the shader of the "optifine-compat" branch so that's why it didn't work ^^'

**Comment by Godlander** [comment]
i will add it next update, currently rewriting some formatting stuff and then will probably merge the two to just be one version that supports optifine but also doesn't lose out on anything
