### ISSUE TITLE
crashes when i run objmc.py

### ISSUE THREAD

**Issue by sussymonke21** [Godlander/objmc#86]
**Description**
crashes when i run objmc.py

**Reproduction**
install python 3.13 install pillow run objmc.py

**Screenshots**
https://drive.google.com/file/d/1IAxbdG5SkuuyXTREvjNWK3N5nKMscQwD/view?usp=sharing

**Environment:**
- windows 11 home
- 1.21.3
- AMD Radeon(TM) Graphics / Radeon RX 5500M

**Additional Information**
I followed [this](https://www.youtube.com/watch?v=VLxg8s4kjDs&t=1s) guide

**Comment by Godlander** [comment]
error message says `No module named 'PIL'`

looks like PIL is still not properly installed, not a bug with objmc itself.

**Comment by sussymonke21** [comment]
When i use the python3 command it says 

`'python3' is not recognized as an internal or external command, operable program or batch file.`

 but when i use the python command it still gives me the PIL error

**Comment by sussymonke21** [comment]
and I've located the PIL file on my PC

**Comment by sussymonke21** [comment]
idk how but i just reinstalled everything for the sake of it and it worked! the only difference was i uninstalled ncap so maybe that was the problem
