### ISSUE TITLE
Models are rotating when client version is under 1.21

### ISSUE THREAD

**Issue by MyoWalE** [Godlander/objmc#89]
**Description**
what is the bug?
Models are rotating when i use minecraft 1.20.4 or under

**Reproduction**
just change mc version to 1.20.4

**Screenshots**
https://cdn.discordapp.com/attachments/1262060145827905556/1317910255442853908/2024-12-14_01-06-51.mp4?ex=67606712&is=675f1592&hm=f7502366f525f3d3b3a7aa66e6067183d3eeb73d5683ff74d3c63439fe404b89&

**Environment:**
Windows 
![20241216_024907](https://github.com/user-attachments/assets/edcd6d66-c62d-48fe-a8bc-25ec8b6912f8)

**Additional context**
I already changed version of shaders so many times.

**Comment by Godlander** [comment]
i will only support the latest version, sorry i wont be able to help with past version issues
